### ISSUE TITLE
Thread 'main' panicked

### ISSUE THREAD

**Issue by Squelsh** [google/pix-image-viewer#5]
Thanks for your work! For a short moment I could see some thumbs but then it crashed... :(
Running vanilla Ubuntu 20.04.1 LTS on a Geforce Laptop. Perhaps you have a quick idea what I could try to fix this.

Thanks,
Andy

```
RUST_BACKTRACE=1 pix
[src/database.rs:174] max_id = 139997
thread 'main' panicked at 'attempted to leave type `platform::platform::x11::util::input::PointerState` uninitialized, which is invalid', /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/core/src/mem/mod.rs:659:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panicking.rs:495:5
   1: core::panicking::panic_fmt
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/core/src/panicking.rs:92:14
   2: core::panicking::panic
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/core/src/panicking.rs:50:5
   3: winit::platform::platform::x11::util::input::<impl winit::platform::platform::x11::xdisplay::XConnection>::query_pointer
   4: winit::platform::platform::x11::EventsLoop::process_event
   5: winit::platform::platform::EventsLoop::poll_events
   6: glutin_window::GlutinWindow::poll_event
   7: <glutin_window::GlutinWindow as window::Window>::poll_event
   8: event_loop::Events::next
   9: <piston_window::PistonWindow<W> as core::iter::traits::iterator::Iterator>::next
  10: pix::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by mason-larobina** [comment]
Hi Andy, 

This could have been a bug in an old version of piston/piston_window/glutin. I've just pushed an update updating all dependencies.

Please re-open if you are able to reproduce the crash.

Cheers
